/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.summercoding.bank.ui;

import com.summercoding.bank.controlleur.Controlleur;
import com.summercoding.bank.entities.Admin;
import com.summercoding.bank.entities.Compte;
import com.summercoding.bank.entities.Utilisateur;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Black Baby
 */
public class JFrameSaveCompte extends javax.swing.JFrame {
     Controlleur controlleur = new Controlleur();
     
      JFrameHome homepage ;
      
      String quelaction;
    /**
     * Creates new form JFrameSaveCompte
     * @param action
     * @param idcompte
     * @param hp
     */
    public JFrameSaveCompte(String action,int idcompte , JFrameHome hp) {
             initComponents();
             initOthersComponents(); 
             
             homepage = hp;
             
             quelaction = action;
             
             if(quelaction.equals("Add")){
                 
                 buttonDelete.setVisible(false);
                 buttonUpdate.setVisible(false);
                 labelIdCompte.setVisible(false);
                 champIdcompte.setVisible(false);
                 
             } else{
                 
                 if(quelaction.equalsIgnoreCase("Update")){
                     
                     try {
                         Compte compte = controlleur.routeVersGetDetailsCompte(idcompte);
                         
                         champSolde.setText(compte.getSolde()+"");
                         champIdcompte.setText(compte.getIdcompte()+"");
                         
                         Utilisateur user = controlleur.routeVersGetUtilisateurIduser(compte.getIduser());
                         comboBoxIduser.setSelectedItem(user.getIduser() + " " + user.getLogin());
                         
                         comboBoxIdadmin.setEnabled(true);
                         
                         Admin admin = controlleur.routeVersGetAdminIdadmin(user.getIdAdmin());
                         comboBoxIdadmin.setSelectedItem(admin.getIdadmin()+ " " + admin.getLogin());
                         
                     } catch (SQLException ex) {
                         Logger.getLogger(JFrameSaveCompte.class.getName()).log(Level.SEVERE, null, ex);
                     }
                     
                 }
             }
    }
    
    // methode pour les autres composants 
    private void initOthersComponents(){
        
         try {
             for(Utilisateur user :controlleur.routeVersListAllUtilisateur()){
                 comboBoxIduser.addItem(user.getIduser()+ " " +user.getLogin());
             }
             
             
             for(Admin admin :controlleur.routeVersListAllAdmin()){
                 comboBoxIdadmin.addItem(admin.getIdadmin()+ " " +admin.getLogin());
             }
         } catch (SQLException ex) {
             Logger.getLogger(JFrameSaveCompte.class.getName()).log(Level.SEVERE, null, ex);
         }
         
         comboBoxIdadmin.setEnabled(false); // permet de desactiver la possibilite a un utilisateur de choisirl'id de l'admin
         idadminSelonIduser();
    }
    
    // methode permettant d'avoir l'id de l'admin selon l'id de l'utilisateur entree
    private void idadminSelonIduser(){
        
         try {
             // recupere l'id de l'utilisateur entrer dans le item et donne ses informations qui sont dans la bd
             String iduserString = comboBoxIduser.getSelectedItem().toString().split(" ")[0];
             int iduser = Integer.parseInt(iduserString);
             
             Utilisateur user = controlleur.routeVersGetUtilisateurIduser(iduser);
            
             
             // recupere l'id de l'admin conaissant l'id de l'utilisateur
             Admin admin = controlleur.routeVersGetAdminIdadmin(user.getIdAdmin());
             comboBoxIdadmin.setSelectedItem(admin.getIdadmin()+ " " + admin.getLogin());
             
         } catch (SQLException ex) {
             Logger.getLogger(JFrameSaveCompte.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        champSolde = new javax.swing.JTextField();
        comboBoxIduser = new javax.swing.JComboBox<>();
        comboBoxIdadmin = new javax.swing.JComboBox<>();
        buttonAdd = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        labelIdCompte = new javax.swing.JLabel();
        champIdcompte = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Solde");

        jLabel2.setText("Iduser");

        jLabel3.setText("Idadmin");

        comboBoxIduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxIduserActionPerformed(evt);
            }
        });

        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        labelIdCompte.setText("Id compte ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelIdCompte, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                    .addComponent(buttonAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(buttonUpdate)
                        .addGap(32, 32, 32)
                        .addComponent(buttonCancel))
                    .addComponent(champSolde)
                    .addComponent(comboBoxIduser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxIdadmin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(champIdcompte))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(champSolde, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboBoxIduser, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addComponent(comboBoxIdadmin))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(champIdcompte, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelIdCompte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdd)
                    .addComponent(buttonCancel)
                    .addComponent(buttonUpdate)
                    .addComponent(buttonDelete))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
         try {
             // TODO add your handling code here:
             
             String  soldeString = champSolde.getText();
             float solde = Float.parseFloat(soldeString);
             if(soldeString.equals("")){
                 JOptionPane.showMessageDialog(null, "Veuillez remplir l'information manquantes");
             }else{
                 
                 String idAdminString =  comboBoxIdadmin.getSelectedItem().toString().split(" ")[0];
                int idAdmin = Integer.parseInt(idAdminString);
            
             
                String iduserString =  comboBoxIduser.getSelectedItem().toString().split(" ")[0];
                int iduser = Integer.parseInt(iduserString);
          
             
                controlleur.routeVersSaveCompte(solde, iduser, idAdmin);
                //JOptionPane.showMessageDialog(null, "Enresgistrement reussi");
             
             
                champSolde.setText("");
             
                this.dispose();
             
                refreshtable();
                 
             }
             String idAdminString =  comboBoxIdadmin.getSelectedItem().toString().split(" ")[0];
             int idAdmin = Integer.parseInt(idAdminString);
            
             
             String iduserString =  comboBoxIduser.getSelectedItem().toString().split(" ")[0];
             int iduser = Integer.parseInt(iduserString);
          
             
             controlleur.routeVersSaveCompte(solde, iduser, idAdmin);
             //JOptionPane.showMessageDialog(null, "Enresgistrement reussi");
             
             
             champSolde.setText("");
             
             this.dispose();
             
             refreshtable();
         } catch (SQLException ex) {
             Logger.getLogger(JFrameSaveCompte.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void comboBoxIduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxIduserActionPerformed
        // TODO add your handling code here:
        idadminSelonIduser();
    }//GEN-LAST:event_comboBoxIduserActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
         try {
             // TODO add your handling code here:

             
             String  soldeString = champSolde.getText();
             float solde = Float.parseFloat(soldeString);
             
             String idAdminString =  comboBoxIdadmin.getSelectedItem().toString().split(" ")[0];
             int idAdmin = Integer.parseInt(idAdminString);
             
             
             String iduserString =  comboBoxIduser.getSelectedItem().toString().split(" ")[0];
             int iduser = Integer.parseInt(iduserString);
             
             
             controlleur.routeVersUpdateCompte(idAdmin, solde, iduser, idAdmin);
             //JOptionPane.showMessageDialog(null, "Enresgistrement reussi");
             
             this.dispose();
             
             refreshtable();
             
             champSolde.setText("");
         } catch (SQLException ex) {
             Logger.getLogger(JFrameSaveCompte.class.getName()).log(Level.SEVERE, null, ex);
         }
             
        
        
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
         try {
             // TODO add your handling code here:
             
             String idCompteString = champIdcompte.getText();
             
             int idcompte = Integer.parseInt(idCompteString);
             
             controlleur.routeVersDeleteCompte(idcompte);
             
             refreshtable();
             
         } catch (SQLException ex) {
             Logger.getLogger(JFrameSaveCompte.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "Desole ce compte ne peut etre supprimé");
         }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameSaveCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameSaveCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameSaveCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameSaveCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameSaveCompte("Add",0,null).setVisible(true);
            }
        });
    }
    
    private void refreshtable() throws SQLException{
        
        List<Compte> listCompte = controlleur.routeVersListAllCompte();
            
            DefaultTableModel modelCompte = new DefaultTableModel();
            
            modelCompte.addColumn("Id");
            modelCompte.addColumn("Solde");
            modelCompte.addColumn("Id user");
            modelCompte.addColumn("Id admin");
            
            for(Compte com : listCompte){
                
                modelCompte.addRow(new String[]{com.getIdcompte()+"",com.getSolde()+"",com.getIduser()+"",com.getIdadmin()+""});
            }
            
            homepage.setQuelmenu("Compte");
            homepage.getTable().setModel(modelCompte);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JTextField champIdcompte;
    private javax.swing.JTextField champSolde;
    private javax.swing.JComboBox<String> comboBoxIdadmin;
    private javax.swing.JComboBox<String> comboBoxIduser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelIdCompte;
    // End of variables declaration//GEN-END:variables
}
