/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.summercoding.bank.ui;

import com.summercoding.bank.controlleur.Controlleur;
import com.summercoding.bank.entities.Admin;
import com.summercoding.bank.entities.Compte;
import com.summercoding.bank.entities.Utilisateur;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Black Baby
 */
public class JFrameHome extends javax.swing.JFrame {
    
    // ceration de l'objet controlleur
    Controlleur controlleur = new Controlleur();
    
    String quelmenu;
    

    /**
     * Creates new form JFrameHome
     */
    public JFrameHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu10 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        menuCreerAdmin = new javax.swing.JMenuItem();
        menuListerAdmin = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuCreerUser = new javax.swing.JMenuItem();
        menuListerUser = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuCreerCompte = new javax.swing.JMenuItem();
        menuListerCompte = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenu10.setText("jMenu10");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        jMenu6.setText("Admin");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });

        menuCreerAdmin.setText("Créer");
        menuCreerAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCreerAdminActionPerformed(evt);
            }
        });
        jMenu6.add(menuCreerAdmin);

        menuListerAdmin.setText("Lister");
        menuListerAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListerAdminActionPerformed(evt);
            }
        });
        jMenu6.add(menuListerAdmin);

        jMenuBar2.add(jMenu6);

        jMenu7.setText("User");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });

        menuCreerUser.setText("Créer");
        menuCreerUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCreerUserActionPerformed(evt);
            }
        });
        jMenu7.add(menuCreerUser);

        menuListerUser.setText("Lister");
        menuListerUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListerUserActionPerformed(evt);
            }
        });
        jMenu7.add(menuListerUser);

        jMenuBar2.add(jMenu7);

        jMenu8.setText("Compte");

        menuCreerCompte.setText("Créer");
        menuCreerCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCreerCompteActionPerformed(evt);
            }
        });
        jMenu8.add(menuCreerCompte);

        menuListerCompte.setText("Lister");
        menuListerCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListerCompteActionPerformed(evt);
            }
        });
        jMenu8.add(menuListerCompte);

        jMenuBar2.add(jMenu8);

        jMenu1.setText("A propos");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Aide");
        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuListerUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListerUserActionPerformed
        
           
        quelmenu = "User";
        
        try {
            // TODO add your handling code here:
         
            
            // appeler de la methode routeVersListAllutilisateur
            List<Utilisateur> listUser  = controlleur.routeVersListAllUtilisateur();
       
            // instruction permettant de recuperer des elements et les mettre dans note table 
            DefaultTableModel modelUser = new DefaultTableModel();
            
            // initialisation des colonnes de notre table 
            modelUser.addColumn("Id");
            modelUser.addColumn("Login");
            modelUser.addColumn("Nom");
            modelUser.addColumn("Prenom");
            modelUser.addColumn("Genre");
            modelUser.addColumn("Date");
            modelUser.addColumn("Idadmin");
            
            
            //parcours de la bd pour recuperer la liste des utilisateurs (id,nom,login)
            for(Utilisateur us : listUser){
                modelUser.addRow(new String[]{us.getIduser()+"", us.getLogin(), us.getNom(),us.getPrenom(),us.getGenre(),us.getDatenaiss()+"",us.getIdAdmin()+""});
            }
            table.setModel(modelUser);
            
        } catch (SQLException ex) {
            Logger.getLogger(JFrameHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_menuListerUserActionPerformed

    private void menuCreerAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCreerAdminActionPerformed
        // TODO add your handling code here:
        
        //ouverture de la page Jframe saveAdmin
        new JFrameAdmin("Add",0,this).setVisible(true);
       
    }//GEN-LAST:event_menuCreerAdminActionPerformed

    private void menuCreerUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCreerUserActionPerformed
        // TODO add your handling code here:
    
        // ouverture de la page saveUser 
        new JFrameSaveUtilisateur("Add", 0, this).setVisible(true);
      
    }//GEN-LAST:event_menuCreerUserActionPerformed

    private void menuListerAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListerAdminActionPerformed
       
        quelmenu = "Admin";
        
        try {
            // TODO add your handling code here:
            List<Admin> listAdmin  = controlleur.routeVersListAllAdmin();
            
            //instruction permettant de recuperer les valeurs de la table 
            DefaultTableModel model = new DefaultTableModel();
            
            //initialisateion des colonnes de motre table 
            model.addColumn("Id");
            model.addColumn("Nom");
            model.addColumn("Login");
            
            //parcours de la bd pour recuperer la liste des admins (id ,nom,login)
            for(Admin ad : listAdmin)
                model.addRow(new String[]{ad.getIdadmin()+"", ad.getNom(), ad.getLogin()});
            
           table.setModel(model);
           
        } catch (SQLException ex) {
            Logger.getLogger(JFrameHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_menuListerAdminActionPerformed

    private void menuListerCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListerCompteActionPerformed
        
        quelmenu = "Compte";
        try {
            // TODO add your handling code here:
            
            List<Compte> listCompte = controlleur.routeVersListAllCompte();
            
            DefaultTableModel modelCompte = new DefaultTableModel();
            
            modelCompte.addColumn("Id");
            modelCompte.addColumn("Solde");
            modelCompte.addColumn("Id user");
            modelCompte.addColumn("Id admin");
            
            for(Compte com : listCompte){
                
                modelCompte.addRow(new String[]{com.getIdcompte()+"",com.getSolde()+"",com.getIduser()+"",com.getIdadmin()+""});
            }
            
            table.setModel(modelCompte);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameHome.class.getName()).log(Level.SEVERE, null, ex);
           
        }
    }//GEN-LAST:event_menuListerCompteActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        
        int numeroLigne = table.getSelectedRow();
        TableModel model = table.getModel();
       
        //cas ou le menu c'est l'admin

        if(quelmenu.equals("Admin")){
            
            //lecture d'une celllule du tableau
            String idAdminString = model.getValueAt(numeroLigne, 0).toString();
            int idadmin = Integer.parseInt(idAdminString);
            
            JFrameAdmin jFrameAdmin = 
                    new JFrameAdmin("Update", idadmin, this);
            jFrameAdmin.setVisible(true);
        }
        else{
            
            //cas ou le menu c'est l'user
             if(quelmenu.equals("User")){
                String idUserString = model.getValueAt(numeroLigne, 0).toString();
            
                int iduser = Integer.parseInt(idUserString);
            
                JFrameSaveUtilisateur jFrameUser = new JFrameSaveUtilisateur("Update", iduser, this);
            
                jFrameUser.setVisible(true);
            }
             else{
                 //cas ou le menu c'est le compte 
                 if(quelmenu.equals("Compte")){
                     
                     String idCompteString = model.getValueAt(numeroLigne, 0).toString();
                     
                     int idcompte = Integer.parseInt(idCompteString);
                     
                     JFrameSaveCompte jFrameCompte = new JFrameSaveCompte("Update", idcompte, this);
                     
                     jFrameCompte.setVisible(true);
                 }
             }
        }
        
       
        
    }//GEN-LAST:event_tableMouseClicked

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6MouseClicked

    private void menuCreerCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCreerCompteActionPerformed
        // TODO add your handling code here:
        
        // ouverture du jframe save compte 
        new JFrameSaveCompte("Add", 0, this).setVisible(true);
    }//GEN-LAST:event_menuCreerCompteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameHome().setVisible(true);
            }
        });
    }

    public JTable getTable() {
        return table;
    }

    public void setTable(JTable table) {
        this.table = table;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem menuCreerAdmin;
    private javax.swing.JMenuItem menuCreerCompte;
    private javax.swing.JMenuItem menuCreerUser;
    private javax.swing.JMenuItem menuListerAdmin;
    private javax.swing.JMenuItem menuListerCompte;
    private javax.swing.JMenuItem menuListerUser;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
